### ISSUE TITLE
Create recorded demo of website

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#100]
## Describe the Task ##
Since the system has no public facing access to view the website and products, create a short demo video to give users a tour of what it looks like and post on the website homepage. 

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
December 5, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Need to ask Cindy or Paul where we can store the media content.

**Comment by hahnd** [comment]
Please see video in the Google Drive.  Uploading now -- needs 5 more minutes.
https://drive.google.com/drive/folders/1iTE7rR2A6bDr37h7q_AKqGYw7rfiC9ZA

**Comment by fossell** [comment]
@hahnd - The video looks great. Thanks so much for doing this. It's a great demo of what the actual product is. I like the last slide with the QR code to the install page of the UG...great idea!

**Comment by fossell** [comment]
The video has been uploaded to the [RAL youtube channel](https://www.youtube.com/watch?v=B1Z-NWrCtXQ) and embedded in the website (will go live after additional mods made).
