### ISSUE TITLE
Post-processing fails for runs with sub-hourly output

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#113]
## Describe the Problem ##
The GeoJson converter fails to convert all GRIB output to GeoJson because [the UPP class generates the wrong GRIB file name](https://github.com/NCAR/wrfcloud/blob/678efe9b9eb22a287149db5cd20516f8d72550a1/python/src/wrfcloud/runtime/postproc.py#L124) for runs with sub-hourly output.

### Expected Behavior ###
For example, with 30 minute output, the converter will look for `/data/test_run/upp/fhr_001/WRFPRS.GrbF01` instead of `/data/test_run/upp/fhr_001/WRFPRS.GrbF00.30`

### Environment ###
ParallelCluster (wrfcloud-cluster)

### To Reproduce ###
Submit a run with 30m or 15m output frequency.

**Comment by fossell** [comment]
Fix was merged into Auto Install branch (PR #114)
