### ISSUE TITLE
Fix sub-hourly WRF output frequencies

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/wrfcloud#142]
## Describe the Problem ##
While working on #126 and testing a new installation of WRF Cloud, I tried running the default Caribbean domain to request a 6 hour run with 15 minute output.

The WRF job completed very quickly and served up the "Open Viewer" button to indicate that the run was finished. However, no plots were actually available there.

This task is address that issue. Options include:
- Removing the ability to request sub-hourly (15 and 30 min) output from the UI entirely.
- Debugging and fixing this behavior directly.

### Expected Behavior ###
If the UI supports requesting sub-hourly WRF output, then it should be produced and viewable.

### Environment ###
Describe your runtime environment:
Ran on app.metpluscloud.org in the "SubHourlyTest" WRF Job (Job ID = WF4FF6D346B).

### To Reproduce ###
Describe the steps to reproduce the behavior:
Already described above.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project** for development toward the next official release
- [x] Select **Milestone** as the next bugfix version

## Bugfix Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>/main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for support of the current release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>/develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This may be resolved with a bugfix that was made in PR #147 to properly compute the timestamp of the data if the output frequency is not 1 hour.
