### ISSUE TITLE
3D temperature at upper levels not displaying

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#162]
## Describe the Problem ##
Time Estimate: 3-4d
The 3D temperature fields, e.g. 300 mb, are not displaying when selected. No data is plotted, just basemap shown, unclear whether there is good data just not being plotted because it's off the color scale or if there is no data. 

If the color scale is just not big enough, need to adjust accordingly. 
Better yet, should define a separate range for each vertical pressure level.

### Expected Behavior ###
All 3D temperature fields at each height should display. 

### Environment ###
Describe your runtime environment:
1. On WRF Cloud forecast viewer

### To Reproduce ###
Describe the steps to reproduce the behavior:
1. Open a forecast viewer for a wrf run
2. Click Temperature (3D)
3. Toggler the vertical slide selector on all possible levels
4. Observe the upper levels do not plot data

### Relevant Deadlines ###
March 24, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select first **Project** for support of the current release
- [ ] Select second **Project** for development toward the next official release
- [ ] Select **Milestone** as the next bugfix version

## Bugfix Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>/main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for support of the current release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>/develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by fossell** [comment]
@hahnd - [This link](https://docs.google.com/document/d/1zGFmjZk0aBCRm8APGMZg8txfAaFQH_bH_yK14Grzj8k/edit?disco=AAAArNSx4Os) goes to a comment on the products page and the table that lists some of the ranges for 3D fields. As I mention in the comment, there are no ranges for temperature at higher levels, e.g. 300, 250, 100mb, because it is not really done or used in practice. So options could be, 1) we inspect the data and make a range we think is suitable for those upper levels, or 2) since it's not really used, we may need to consider how to better indicate fields that do not or should not have data. First, however, we should probably confirm that there is data present at those levels in the grib files.

**Comment by fossell** [comment]
Plan is to create a dynamic color range for each level. When selecting a 3D field, the legend label will expand with added characters to indicate the current level, e.g. 1000mb, and teh color scale will be the one defined for that level. When selecting a new level, the level descriptor in the legend label will also change, along with the color scale to be that of the current level selected.

**Comment by fossell** [comment]
@hahnd - Related to comments in this issue for needing unique ranges for each vertical level for temperature, this is necessary for winds too. Is it possible to make mods to all 3D fields to have unique ranges for each level as part of this issue? 

Example of wind speeds going off the chart. Note that @georgemccabe will be updating the max value for wind speeds to 120kts since the value of 60 was for m/s. But even 120 probably won't be sufficient for upper level wind speeds, at least in mid-latitude domains.
![image](https://user-images.githubusercontent.com/17770149/230413887-dc946c9f-1707-46d4-9774-564ce44391ad.png)

**Comment by hahnd** [comment]
Yes, it is my plan to make changes that can be applied to all variables, not just the temperature.
