### ISSUE TITLE
ParallelCluster Version

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#165]
## Describe the Problem ##
Received an email from AWS regarding ParallelCluster:

> AWS is aware of an issue affecting Intel (R) MPI library versions prior to 2021.6 [1], distributed with AWS ParallelCluster versions 3.2.0 and earlier. This issue does not impact the operation of clusters managed using ParallelCluster, but we recommend updating the Intel (R) MPI library to 2021.6 by recreating clusters using ParallelCluster version 3.2.1 or later. You can also manually update the Intel (R) MPI library to 2021.6 on your existing clusters by following these instructions [2]. Recreated clusters will be running Intel (R) MPI library version 2021.6. 

We already use [ParallelCluster v3.2.1](https://github.com/NCAR/wrfcloud/blob/2c244baf14a89c4d38afbed8dcd2f45e83368a02/python/src/setup.py#L20), so maybe this does not affect us.

If we decide to upgrade, we should switch to the current latest version, which is 3.5.0.

To upgrade, we would need to do the follow at a minimum:
- Change [pcluster version dependency](https://github.com/NCAR/wrfcloud/blob/2c244baf14a89c4d38afbed8dcd2f45e83368a02/python/src/setup.py#L20)
- Change the [parent AMI ID](https://github.com/NCAR/wrfcloud/blob/2c244baf14a89c4d38afbed8dcd2f45e83368a02/python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml#L722) for our ImageBuilder configuration
- Replace the ImageBuilder stack: `wrfcloud-imagebuilder replace`
- Build a new AMI `wrfcloud-imagebuilder build`

Additionally, we may need to:
- Update the [Intel packages installed](https://github.com/NCAR/wrfcloud/blob/2c244baf14a89c4d38afbed8dcd2f45e83368a02/python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml#L36):
- Depending on version changes, it is possible the [pcluster configuration](https://github.com/NCAR/wrfcloud/blob/develop/python/src/wrfcloud/aws/resources/cluster.wrfcloud.yaml) needs to be updated.

Other considerations:
- The issue is regarding MPI.  We have been running WRF without issues for the duration of the project.
- AWS identified the issue with pcluster <= v3.2.0.  We are using v3.2.1.

@fossell - Can you please review and prioritize this issue?

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select first **Project** for support of the current release
- [ ] Select second **Project** for development toward the next official release
- [ ] Select **Milestone** as the next bugfix version

## Bugfix Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>/main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for support of the current release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>/develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by fossell** [comment]
Does not impact our system.
