### ISSUE TITLE
weblink dead

### ISSUE THREAD

**Issue by HathewayWill** [NCAR/wrfcloud#196]
*Replace italics below with details for this issue.*

## Describe the Problem ##
wrfcloud.com error 404

### Expected Behavior ###
should load website

### Environment ###
Describe your runtime environment:
Desktop
Ubuntu 22.02

### To Reproduce ###
Describe the steps to reproduce the behavior:
Click on weblink in readme

**Comment by hahnd** [comment]
Hi @HathewayWill,

Thank you for sending this report.  

I just tested this from my mac and it was successful from multiple browsers (Firefox, Chrome, Safari, Brave) as well as command line utilities (wget and curl).  

Which browser are you using?

Any HTTP request should automatically be redirected to HTTPS, but maybe try adding the [https://wrfcloud.com](https://wrfcloud.com) or [https://www.wrfcloud.com](https://www.wrfcloud.com) to the URL.

If you are looking to install the system in your AWS account, the instructions to do that are here: [https://wrfcloud.readthedocs.io/en/stable/](https://wrfcloud.readthedocs.io/en/stable/).

**Comment by fossell** [comment]
@hahnd - I was just able to reproduce this on my Mac, just clicking on the wrfcloud.com link on the README.md shown on the repo main page. I looked at the file and probably just need to add https:// to that link in the markdown page. I can make that mod quickly.

**Comment by fossell** [comment]
@HathewayWill - Can you confirm that link in the README works now? It works on my end.

**Comment by HathewayWill** [comment]
Yes the issue is now fixed.
