### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by jwolff-ncar** [NCAR/wrfcloud#2]

**Comment by fossell** [comment]
Codebuild is implemented on AWS, need to integrate into Github.
@JohnHalleyGotway - Will look into Github

**Comment by JohnHalleyGotway** [comment]
- [x] Embedded a code coverage badge into a top-level README file using:
   https://codecov.io/gh/<your-organisation>/<your-project>/settings/badge
For this project that's:
   https://codecov.io/gh/ncar/wrfcloud/settings/badge

- [ ] Will integrate code coverage checks into GitHub PR's following these instructions:
   https://docs.codecov.com/docs/github-checks

**Comment by JohnHalleyGotway** [comment]
Inspecting [AWS wrfcloud code builds](https://us-east-2.console.aws.amazon.com/codesuite/codebuild/119569266530/projects/wrfcloud/history?region=us-east-2&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjoyfQ), I note that the behavior changed between run numbers [161](https://us-east-2.console.aws.amazon.com/codesuite/codebuild/119569266530/projects/wrfcloud/build/wrfcloud%3A14f936a1-5e87-4f90-956e-88231f519b94/?region=us-east-2) and [162](https://us-east-2.console.aws.amazon.com/codesuite/codebuild/119569266530/projects/wrfcloud/build/wrfcloud%3A99b42e5f-546e-4299-82b9-e27716989c8c/?region=us-east-2). The latter introduced an authentication error:
```
[Container] 2022/09/20 20:28:07 Waiting for DOWNLOAD_SOURCE
--
4 | authentication required for primary source and source version 2683de9e84dfaf842fc0cdec44739505a6fb760e
```
