### ISSUE TITLE
Incorrect version number in v1.1.0 tag

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#230]
## Describe the Problem ##
The version number displaying in RTD title for this build (and maybe other places) reads "v1.1.0-rc1" (e.g. [here](https://wrfcloud.readthedocs.io/en/v1.1.0/)). The [VERSION](https://github.com/NCAR/wrfcloud/blob/69afa9b6b3dfaa20ed5969c75aa62edfcf011f97/python/src/wrfcloud/VERSION#L1) and [RELEASE_DATE](https://github.com/NCAR/wrfcloud/blob/69afa9b6b3dfaa20ed5969c75aa62edfcf011f97/python/src/wrfcloud/RELEASE_DATE#L1) files were not updated.

### Expected Behavior ###
Version should be updated and read "v1.1.0" in RTD for this [release build](https://wrfcloud.readthedocs.io/en/v1.1.0/) and on [stable build](https://wrfcloud.readthedocs.io/en/stable/).

### Environment ###
RTD User Guides

### To Reproduce ###
See [here](https://wrfcloud.readthedocs.io/en/v1.1.0/).

### Relevant Deadlines ###
Aug 1, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select first **Project** for support of the current release
- [x] Select second **Project** for development toward the next official release
- [x] Select **Milestone** as the next bugfix version

## Bugfix Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>/main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for support of the current release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>/develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by fossell** [comment]
@georgemccabe - I missed these updates for the release. I'll put them into main and retag the release. Should the updates also go into develop for consistency?

**Comment by georgemccabe** [comment]
Ah, yes I didn't notice this. This doesn't need to go into develop because the version number was updated for future development.

**Comment by fossell** [comment]
Closed with #231
