### ISSUE TITLE
Generate data for multiple CIMH domains and cases

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#41]
This is a sub-issue of #40 

## Describe the Sub-Issue ##
Generate data for multiple CIMH domains and cases to be archived for later evaluation and verification. Cheyenne resources available to use before Oct 1. 

Experiments to run:
1. 4 domains
2. 5th domain that'a union of all 4 (if time/resources allow)
3. For each domain, 1-2 high impact events and 1 week (or more, if time/resources allow) period of 00z initializations

@michelleharrold will initiate the task to get things set up and ready to run. Will assign specific tasks at future meeting. 

### Time Estimate ###
1 month. Resources expire Sep 30, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

**Comment by fossell** [comment]
Current plan is to run 00Z and 12Z initializations for August 2021 - early/mid-September 2021 to capture a longer period and several hurricane cases within that time period.

**Comment by fossell** [comment]
Forecast length?  As long as possible with given resources? Perhaps run a forecast for each domain to get some time/resource estimates and we can go from there.

**Comment by michelleharrold** [comment]
After some benchmarking, to run 120-h (5-day) forecasts for the 12-km full Caribbean and 4-km W. Caribbean, S. Caribbean, and E. Caribbean, it would take a little under 200K core hours for 70 inits (00 and 12 UTC from Aug. 1 - Sept. 4, 2021). I also ran 72-h (3-day) and 48-h (2-day) -- those would be a little over 100K and 70K, respectively.
