### ISSUE TITLE
Incorrect linking of GFS files for use in ungrib.exe

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#65]
## Describe the Problem ##
The GFS files are linked to GRIBFILE.AA* series in the incorrect order, i.e. not in sequential time increasing order. It does not cause anything to fail, but definitely not going to produce correct results. Guessing this is an issue in ungrib.py somewhere and how the files are sorted. The issue occurs when pulling data from NOMADS or S3 on both Cheyenne and AWS. It did not occur using local GFS test data.  Note below how GRIBFILE.AAA is linked to f009, but it should be the first in time, e.g. f000.  

GRIBFILE.AAA -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f009
GRIBFILE.AAB -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f000
GRIBFILE.AAC -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f006
GRIBFILE.AAD -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f003
GRIBFILE.AAE -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f012

### Expected Behavior ###
Expected to see:
GRIBFILE.AAA -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f000
GRIBFILE.AAB -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f003
GRIBFILE.AAC -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f006
GRIBFILE.AAD -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f009
GRIBFILE.AAE -> /data/testrun/ungrib/gfs.t06z.pgrb2.0p25.f012

### Environment ###
Describe your runtime environment:
1. Machine: Cheyenne and AWS wrfcloud cluster
2. OS: Linux
3. n/a

### To Reproduce ###
Describe the steps to reproduce the behavior:
1. Checkout develop branch and set up a test
2. Edit run.yml to set local_data to empty string, e.g.:
`local_data: '' `
4. Run the run.py
5. Check the output/ungrib and do an ` ls -l ` to the see the incorrect linking

### Relevant Deadlines ###
Sep 30

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select first **Project** for support of the current release
- [ ] Select second **Project** for development toward the next official release
- [x] Select **Milestone** as the next bugfix version

## Bugfix Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>/main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for support of the current release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>/develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by mkavulich** [comment]
I see the problem. The "glob" filelist for the remote data retrieval needs to be sorted alphabetically just like the local data, since glob.glob returns a list of files that is not guaranteed any particular sorting.

https://stackoverflow.com/questions/6773584/how-are-glob-globs-return-values-ordered

[Line 51 in ungrib.py](https://github.com/NCAR/wrfcloud/blob/develop/python/src/wrfcloud/runtime/ungrib.py#L51) needs to be 
```
            filelist = sorted(glob.glob(os.path.join(self.runinfo.ungribdir, 'gfs.*')))
```

The `sorted` function sorts the list alphabetically by default, which is the same behavior that the WPS link_grib.csh script shows.

**Comment by fossell** [comment]
@mkavulich - Thanks! I see it now. I can create a feature branch and test this tomorrow.
