### ISSUE TITLE
API Audit Logs

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#7]
## Describe the New Feature ##
The API should log details for each request received.  This will help to locate error logs when users report problems and  track system activity.

### Acceptance Testing ###
The current tests for the API handler can be updated to make sure there is an entry in the *audit log* database table and that values are set appropriately for the test request.

### Time Estimate ###
8h

### Relevant Deadlines ###
NONE

### Assignee ###
- [X] @hahnd

### Labels ###
- [X] API
- [X] High

### Projects and Milestone ###
- [X] wrfcloud
- [X] Version 0.1

## New Feature Checklist ##
- [x] AuditEntry class to store log entry properties
- [x] AuditDao class (Data access object) to handle DynamoDB transactions
- [x] DynamoDB table definition
- [x] Save method to save a log entry to the audit table
- [x] Read method to read a log entry from the audit table based on reference ID
- [x] Unit tests will sufficient code coverage

Branch name: `feature_<Issue Number>/api-audit-log`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.

Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hahnd FYI, I created a new "component: API" label and added that along with the "priority: high" label. At least that's how I interpreted the content you added under the "Labels" section of the issue template.

I'd recommend you add new [labels](https://github.com/NCAR/wrfcloud/labels), as needed, as you go to help keep the issues organized.
