### ISSUE TITLE
Finalize output product list

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#94]
## Describe the Task ##
Need to complete a config file that lists out the mapping of grib2 variables to plots for the wrfcloud-geojson --auto option (See PR #93, also part of issues #37 and #38). 
List should map grib_dump of fields to the table of products, both found [here](https://docs.google.com/document/d/1zGFmjZk0aBCRm8APGMZg8txfAaFQH_bH_yK14Grzj8k/edit). 

### Time Estimate ###
2 hours, plus trouble shooting

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
December 5, 2022 V0.1 release, but need this completed sooner, probably November 11 to make sure progress is made. 

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by michelleharrold** [comment]
@hahnd and @fossell - using the grib_dump info at the bottom of the [google doc](https://docs.google.com/document/d/1zGFmjZk0aBCRm8APGMZg8txfAaFQH_bH_yK14Grzj8k/edit), I filled in the two tables for surface/column and upper-air variables to also include the pygrib variable name of the UPP output. I put it under the column name: Name (from UPP/Grib2 shortName). Let me know if you have any questions!

**Comment by fossell** [comment]
@michelleharrold - Thank you!
